networks:
  portfolio_net:
    external: true

services:
  frontend:
    image: portfolio:latest
    build:
      context: .
    ports:
      - "7002:80"
    restart: unless-stopped
    networks:
      - portfolio_net

  backend:
    image: backend:latest
    build:
      context: ./backend
    ports:
      - "7001:7001"
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@postgres:5432/portfolio_db
    depends_on:
      - postgres
    networks:
      - portfolio_net

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=portfolio_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - portfolio_net

volumes:
  postgres_data:
