version: "3.9"

services:
  frontend:
    image: portfolio:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:80"   
    restart: unless-stopped

  backend:
    image: backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7001:7001"
    restart: unless-stopped
