export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
        headline: ['"Space Grotesk"', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        '128': '32rem',
      },
      colors: {
        "inverse-primary": "#94ccff",
        "on-error-container": "#93000a",
        "tertiary": "#00564f",
        "error-container": "#ffdad6",
        "surface-container": "#e7eeff",
        "on-tertiary-fixed-variant": "#005049",
        "on-tertiary-container": "#88f4e6",
        "surface-variant": "#d8e3fb",
        "background": "#f9f9ff",
        "on-secondary-fixed": "#0d1c2e",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f0f3ff",
        "secondary-fixed": "#d5e3fc",
        "on-error": "#ffffff",
        "secondary-container": "#d5e3fc",
        "surface-tint": "#006399",
        "on-secondary-fixed-variant": "#3a485b",
        "on-secondary-container": "#57657a",
        "inverse-surface": "#263143",
        "surface-container-highest": "#d8e3fb",
        "on-background": "#111c2d",
        "inverse-on-surface": "#ecf1ff",
        "surface-dim": "#cfdaf2",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#dee8ff",
        "tertiary-fixed": "#89f5e7",
        "on-surface": "#111c2d",
        "on-primary-fixed": "#001d32",
        "tertiary-container": "#007167",
        "primary-container": "#0369a1",
        "outline": "#707881",
        "on-primary-container": "#cbe4ff",
        "surface": "#f9f9ff",
        "secondary-fixed-dim": "#b9c7df",
        "surface-bright": "#f9f9ff",
        "outline-variant": "#c0c7d1",
        "on-primary": "#ffffff",
        "on-surface-variant": "#40474f",
        "secondary": "#515f74",
        "primary-fixed": "#cde5ff",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#004b74",
        "tertiary-fixed-dim": "#6bd8cb",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#94ccff",
        "on-tertiary-fixed": "#00201d",
        primary: {
          DEFAULT: '#00507d',
          50: '#f0f0f0',
          100: '#e0e0e0',
          200: '#c2c2c2',
          300: '#a3a3a3',
          400: '#858585',
          500: '#666666',
          600: '#525252',
          700: '#3d3d3d',
          800: '#292929',
          900: '#141414',
        },
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'fade-in-up': 'fadeInUp 0.5s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
};